library(ggvis)
library(shinyBS)

# For dropdown menu
actionLink <- function(inputId, ...) {
  tags$a(href='javascript:void',
         id=inputId,
         class='action-button',
         ...)
}


# Define the overall UI
shinyUI(#fluidPage(
  pageWithSidebar( 
  #titlePanel("Interactive Data Tool"),
headerPanel("Interactive Data Tool"),
  #fluidRow(
  sidebarPanel(width = 3,
 #   column(10,
           wellPanel(
             h4("Filter"),

              selectInput("Position", "Most Recent Placement", c("All", "Tenure-Track", "Other Permanent Position", "Fellowship/Postdoc",
                                                               "Visiting Position", "Other Temporary Position", "Non-academic Position"), selected = "ALL"),
                           #"Nonacademic Placement", "No Placement")
             sliderInput("Graduation_year", "Year Doctorate Obtained*", 1994,2017, 
                         value = c(2006, 2016), sep = ""), 
             h6(textOutput("text1")),
            selectInput("aos", "Area of Specialty (AOS)", c("All", aos_lev),
                        selected = "All"),
#uiOutput("Box1"),
uiOutput("Box2"),
#            selectInput("primaos", "Primary Area of Specialty", primaryAoSlevels 
#                        , selected = "ALL"),
        #      textInput("Phdfrom", "Institution name contains (e.g., California)")

       selectInput("Phdfrom", "University", choices = c("All", "Arizona State University",
                                                        "Australian National University*",
                                                        "Baylor University",
                                                        "Bielefeld University*",
                                                        "Birkbeck, University of London*",
                                                        "Boston College",
                                                        "Boston University",
                                                        "Bowling Green State University",
                                                        "Brandeis University*",
                                                        "Brown University",
                                                        "California Institute of Technology*",
                                                        "Carnegie Mellon University",
                                                        "Central European University",
                                                        "Claremont Graduate University*",
                                                        "Columbia University",
                                                        "Cornell University",
                                                        "Dalhousie University*",
                                                        "Deakin University*",
                                                        "Delft University of Technology*",
                                                        "DePaul University",
                                                        "Duke University",
                                                        "Duquesne University",
                                                        "Durham University",
                                                        "Eberhard Karls University, bingen*",
                                                        "Emory University",
                                                        "Florida State University",
                                                        "Fordham University",
                                                        "Freie Universität Berlin*",
                                                        "Georgetown University",
                                                        "Goethe University Frankfurt*",
                                                        "Graduate Center of the City University of New York",
                                                        "Harvard University",
                                                        "Humboldt University of Berlin*",
                                                        "Indiana University Bloomington",
                                                        "Indiana University Bloomington (HPS)",
                                                        "Institut Jean Nicod",
                                                        "Iowa State University*",
                                                        "Johannes Gutenberg University of Mainz*",
                                                        "Johns Hopkins University",
                                                        "Katholieke Universiteit Leuven*",
                                                        "King's College London",
                                                        "Kingston University*",
                                                        "Leipzig University*",
                                                        "London School of Economics and Political Science",
                                                        "Loyola University Chicago",
                                                        "Macquarie University",
                                                        "Marquette University",
                                                        "Massachusetts Institute of Technology",
                                                        "McGill University",
                                                        "McMaster University",
                                                        "Michigan State University",
                                                        "Monash University*",
                                                        "Montclair State University*",
                                                        "New York University",
                                                        "Northwestern University",
                                                        "Ohio State University",
                                                        "Pantheon-Sorbonne University*",
                                                        "Pennsylvania State University*",
                                                        "Princeton University",
                                                        "Purdue University",
                                                        "Rutgers University",
                                                        "Saint Louis University*",
                                                        "Scuola Normale Superiore di Pisa*",
                                                        "Simon Fraser University*",
                                                        "Southern Illinois University",
                                                        "St Andrews and Stirling Graduate Programme in Philosophy",
                                                        "Stanford University",
                                                        "State University of New York at Albany*",
                                                        "State University of New York at Binghamton",
                                                        "State University of New York at Buffalo",
                                                        "State University of New York at Stony Brook",
                                                        "Stockholm University*",
                                                        "Syracuse University",
                                                        "Technische Universität Bergakademie Freiberg*",
                                                        "Temple University",
                                                        "Texas State University*",
                                                        "The Catholic University of America",
                                                        "The New School",
                                                        "The University of Adelaide*",
                                                        "The University of Manchester*",
                                                        "The University of Melbourne*",
                                                        "The University of Sydney",
                                                        "The University of Western Australia*",
                                                        "Tilburg University",
                                                        "Trinity College, Dublin*",
                                                        "Tulane University",
                                                        "Universit̩ de Montr̩al*",
                                                        "University College London",
                                                        "University of Aberdeen",
                                                        "University of Alberta",
                                                        "University of Amsterdam*",
                                                        "University of Arizona",
                                                        "University of Auckland*",
                                                        "University of Bristol",
                                                        "University of British Columbia",
                                                        "University of Calgary",
                                                        "University of California, Berkeley",
                                                        "University of California, Davis",
                                                        "University of California, Irvine",
                                                        "University of California, Irvine (LPS)",
                                                        "University of California, Los Angeles",
                                                        "University of California, Riverside",
                                                        "University of California, San Diego",
                                                        "University of California, Santa Barbara",
                                                        "University of California, Santa Cruz",
                                                        "University of Cambridge",
                                                        "University of Chicago",
                                                        "University of Chicago (CHSS)",
                                                        "University of Cincinnati",
                                                        "University of Cologne*",
                                                        "University of Colorado at Boulder",
                                                        "University of Connecticut",
                                                        "University of Dallas",
                                                        "University of Dundee",
                                                        "University of East Anglia*",
                                                        "University of Edinburgh",
                                                        "University of Erfurt*",
                                                        "University of Florida",
                                                        "University of Geneva*",
                                                        "University of Georgia",
                                                        "University of Glasgow*",
                                                        "University of Graz*",
                                                        "University of Groningen*",
                                                        "University of Guelph",
                                                        "University of Hawai'i at Ṃnoa*",
                                                        "University of Helsinki*",
                                                        "University of Illinois at Chicago",
                                                        "University of Illinois at Urbana-Champaign",
                                                        "University of Iowa",
                                                        "University of Kansas*",
                                                        "University of Kentucky",
                                                        "University of Leeds*",
                                                        "University of Maryland, College Park",
                                                        "University of Massachusetts Amherst",
                                                        "University of Memphis",
                                                        "University of Miami",
                                                        "University of Michigan",
                                                        "University of Milan*",
                                                        "University of Minnesota Twin Cities",
                                                        "University of Missouri",
                                                        "University of Modena*",
                                                        "University of Nebraska-Lincoln",
                                                        "University of New Mexico",
                                                        "University of New South Wales*",
                                                        "University of North Carolina at Chapel Hill",
                                                        "University of Notre Dame",
                                                        "University of Oklahoma*",
                                                        "University of Oregon",
                                                        "University of Oslo*",
                                                        "University of Otago*",
                                                        "University of Ottawa*",
                                                        "University of Oxford",
                                                        "University of Padua*",
                                                        "University of Pennsylvania",
                                                        "University of Pittsburgh",
                                                        "University of Pittsburgh (HPS)",
                                                        "University of Reading",
                                                        "University of Rochester",
                                                        "University of Sheffield",
                                                        "University of South Carolina",
                                                        "University of South Florida",
                                                        "University of Southern California",
                                                        "University of Sussex",
                                                        "University of Tasmania*",
                                                        "University of Tehran*",
                                                        "University of Tennessee",
                                                        "University of Texas at Austin",
                                                        "University of Toronto",
                                                        "University of Utah",
                                                        "University of Vienna*",
                                                        "University of Virginia",
                                                        "University of Waikato*",
                                                        "University of Warwick",
                                                        "University of Washington",
                                                        "University of Waterloo*",
                                                        "University of Western Ontario",
                                                        "University of Wisconsin-Madison",
                                                        "University of York",
                                                        "Uppsala University*",
                                                        "Vanderbilt University",
                                                        "Victoria University of Wellington*",
                                                        "Villanova University",
                                                        "Washington University in St. Louis",
                                                        "Wayne State University*",
                                                        "William Marsh Rice University",
                                                        "Yale University",
                                                        "York University"
       ), selected = "ALL"
       ),
h6(textOutput("text2"))
           ),
           wellPanel(
             selectInput("legendvar", "Legend",
                         legend_vars, selected = "has_gender"),
             selectInput("xvar", "X-axis variable", axis_vars, selected = "graduation_year")
#             selectInput("yvar", "Y-axis variable", axis_vars, selected = "position")
             )
    ),#),
mainPanel(
tabsetPanel(
  tabPanel("Main",
#conditionalPanel("output.test >= 1",
 #   column(9,
bsAlert("alert2"),
         #  conditionalPanel("output.n_col == 14 ", 
         ggvisOutput("plot1"),
           
                            #ggvisOutput("plot1"),
         
                bsAlert("alert") #,
#           wellPanel(
#             span("Number of cases:",
#                  textOutput("n_graduates")
#                )
#           )
  #  )
  ),
tabPanel("Table",dataTableOutput("mytable"), bsAlert("alert"))
))
    
))